In [1]:
import argparse
import datetime
import os, sys
import os.path as osp
sys.path.insert(0, '../')
import torch
import yaml
import numpy as np

from models.unet.unet_model import UNet
from utils.generators import DataGenerator
from global_config import global_config
from summary.unet_test import test

In [2]:
save_dir = '/home/warit/fcn_senior/experiments/unet/unet_logs/logs_3_1_03011438'
config = {
    'DEVICE': torch.device('cuda:0'),
    'IN_LEN': 3,
    'OUT_LEN': 1,
    'BATCH_SIZE': 4,
    'SCALE': 0.25,
    'TASK': 'reg',
    'DIM': '2D',
}

In [3]:
data_loader = DataGenerator(data_path=global_config['DATA_PATH'], config=config)
n_classes = 1
if 'seg' in config['TASK']:
    n_classes = 4
model = UNet(n_channels=config['IN_LEN'], n_classes=n_classes)
model = torch.nn.DataParallel(model, device_ids=[0, 2])
model = model.to(config['DEVICE'])
weight_path = save_dir + '/model_8000.pth'
test(model, weight_path, data_loader, config, save_dir, crop=None)

100%|██████████| 1/1 [00:58<00:00, 58.51s/it]


In [4]:
np.load(save_dir+'/result.npz', allow_pickle=True)['r']

array([1.5000716227218172, 6.6559692599819105, 0.41683396408041623,
       57.5355829136297,
       array([97.50902859, 52.54113036,  8.12530621,  0.59049786])],
      dtype=object)

In [5]:
# array([1.619398721481633, 6.975028940888992, 0.5912824876899682,
#        54.93729698329912,
#        array([97.51818811, 51.28427175,  6.3821027 ,  2.25145917])],
#       dtype=object)